### ISSUE TITLE
debugging devise async

### ISSUE THREAD

**Issue by rubytastic** [mhfs/devise-async#41]
Are there any methods to better debug devise-async? it seems to not work I get sidekiq error reports without a actual trace. 

Can one use the rails console to send mails true async to test what goes wrong and where? very hard to debug else

I only get this without real application code trace

A Redis::CommandError occurred in background at 2013-10-18 00:44:55 +0200 :

 EXECABORT Transaction discarded because of previous errors.
 /srv/books/shared/bundle/ruby/2.1.0/gems/redis-3.0.5/lib/redis/pipeline.rb:79:in `finish'

 -------------------------------
Backtrace:
-------------------------------

 /srv/books/shared/bundle/ruby/2.1.0/gems/redis-3.0.5/lib/redis/pipeline.rb:79:in `finish'
 /srv/books/shared/bundle/ruby/2.1.0/gems/redis-3.0.5/lib/redis/client.rb:121:in `block in call_pipeline'
 /srv/books/shared/bundle/ruby/2.1.0/gems/redis-3.0.5/lib/redis/client.rb:245:in `with_reconnect'
 /srv/books/shared/bundle/ruby/2.1.0/gems/redis-3.0.5/lib/redis/client.rb:119:in `call_pipeline'
 /srv/books/shared/bundle/ruby/2.1.0/gems/redis-3.0.5/lib/redis.rb:2125:in `block in multi'
 /srv/books/shared/bundle/ruby/2.1.0/gems/redis-3.0.5/lib/redis.rb:36:in `block in synchronize'
 /usr/local/rvm/rubies/ruby-2.1.0-preview1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
 /srv/books/shared/bundle/ruby/2.1.0/gems/redis-3.0.5/lib/redis.rb:36:in `synchronize'
 /srv/books/shared/bundle/ruby/2.1.0/gems/redis-3.0.5/lib/redis.rb:2117:in `multi'
 /srv/books/shared/bundle/ruby/2.1.0/gems/sidekiq-2.15.1/lib/sidekiq/processor.rb:93:in `block in stats'
 /srv/books/shared/bundle/ruby/2.1.0/gems/connection_pool-1.1.0/lib/connection_pool.rb:49:in `with'
 /srv/books/shared/bundle/ruby/2.1.0/gems/sidekiq-2.15.1/lib/sidekiq.rb:67:in `redis'
 /srv/books/shared/bundle/ruby/2.1.0/gems/sidekiq-2.15.1/lib/sidekiq/util.rb:26:in `redis'
 /srv/books/shared/bundle/ruby/2.1.0/gems/sidekiq-2.15.1/lib/sidekiq/processor.rb:92:in `stats'
 /srv/books/shared/bundle/ruby/2.1.0/gems/sidekiq-2.15.1/lib/sidekiq/processor.rb:46:in `block in process'
 /srv/books/shared/bundle/ruby/2.1.0/gems/sidekiq-2.15.1/lib/sidekiq/processor.rb:83:in `do_defer'
 /srv/books/shared/bundle/ruby/2.1.0/gems/sidekiq-2.15.1/lib/sidekiq/processor.rb:37:in `process'
 /srv/books/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
 /srv/books/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
 /srv/books/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
 /srv/books/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
 /srv/books/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
 /srv/books/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
 /srv/books/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'

-------------------------------
Data:
-------------------------------

 * data: {:message=>
   {"retry"=>true,
    "queue"=>"mailer",
    "class"=>"Devise::Async::Backend::Sidekiq",
    "args"=>
     ["confirmation_instructions", "User", "2", "mJTMoQvAskUPxGuFRegF", {}],
    "jid"=>"20807982a65a94f574313ce0",
    "enqueued_at"=>1382049893.6279392}}

**Comment by baschtl** [comment]
@rubytastic This issue is quiet old. Is there still a need to discuss this? Otherwise, I would like to delete the issue.
