### ISSUE TITLE
:sidekiq backend doesn't register worker

### ISSUE THREAD

**Issue by dalssoft** [mhfs/devise-async#46]
I think it is similar to https://github.com/mhfs/devise-async/issues/30

I have loads of enqueued tasks but none is processed.

The thing is that when I go to /sidekiq page I can't see any worker registered there. 

Any idea?

Info:

    # Gemfile.lock
    rails (4.0.0)
    sidekiq (2.17.2)
    devise (3.2.2)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-async (0.9.0)
      devise (~> 3.2)

    # route.rb
    ....
    devise_for :users, :controllers => {:sessions => "sessions"}

    # model/user.rb
    class User < ActiveRecord::Base
        # Include default devise modules. Others available are:
        # :confirmable, :lockable, :timeoutable and :omniauthable
        devise :database_authenticatable, :async, :registerable, :confirmable,
               :recoverable, :rememberable, :trackable, :validatable
        has_one :consultor
        attr_accessible :username, :email, :password, :password_confirmation, :remember_me,  :name, :confirmed_at, :actived, :consultor

        def only_if_unconfirmed
          pending_any_confirmation {yield}
        end

      end

    # config/initialize/devise_async.rb
    Devise::Async.backend = :sidekiq
    Devise::Async.enabled = true

    # config/sidekiq.yml
    :verbose: true
    :concurrency:  25
    :queues:
      - [mailer, 5]
      - [default, 5]

**Comment by Olgagr** [comment]
```
# config/initializers/devise_async.rb
Devise::Async.setup do |config|
  config.enabled = true
  config.backend = :sidekiq
  config.queue   = :default
end
```

This also works for me. Maybe this is good idea to update README file to include this information for sidekiq backend.

**Comment by daslicious** [comment]
worked for me as well.

**Comment by baschtl** [comment]
Done.
