### ISSUE TITLE
Any option to add delay ?

### ISSUE THREAD

**Issue by skrypalyk** [mhfs/devise-async#54]
Hello!
Sometimes(not always), when creating user with email confirmation I get ActiveRecord::RecordNotFound, because user is not in DB yet, so is it possible to add some delay for email sending ?
Thanks in advance

**Comment by baschtl** [comment]
@skrypalyk Well, the specific backend could have an option for this. For example, delayed job has the `run_at` option that you could use like this: `run_at: -> {  10.minutes.from_now }`. However, these options are not forwarded to the call of the backend as far as I know.

Happy to see a pull request for this, though. :-)

Closing this for now then.
