### ISSUE TITLE
Looking for co-maintainer

### ISSUE THREAD

**Issue by mhfs** [mhfs/devise-async#64]
Hi guys, I'm looking for someone to join me as co-maintainer of devise-async.

I cannot devote the amount of time I'd like to take proper care of this project and having someone to help me would make things quicker and better for everyone.

Desirable characteristics:

* active use of devise-async in live production apps
* history of contributions for OSS

Things I value:

* good test coverage
* good docs in the readme
* backward compatibility
* maintainers consensus on big code refactoring
* maintainers consensus on api changes

Please get in touch.

**Comment by baschtl** [comment]
@mhfs What are your future plans - if any - for `devise-async` since Active Job is out for Rails 4.2?

**Comment by mhfs** [comment]
@baschtl that's part of what I'd want to figure out. I have not worked with latest versions of rails or devise for a while now.

**Comment by baschtl** [comment]
@mhfs Hmm, I also have not looked into Active Job specifically. But I have seen that the supported backends match with few differences. I also saw this one yesterday: https://github.com/ushu/devise-async-activejob.

**Comment by baschtl** [comment]
@mhfs As mentioned in https://github.com/mhfs/devise-async/pull/60 it seems to be pretty easy to use Active Job with devise.

**Comment by baschtl** [comment]
@mhfs Could you push a new release (0.10.0-alpha) to rubygems if possible? That would be great!

**Comment by mhfs** [comment]
hey @baschtl, thanks for all the help with device-async. I'm still super busy and still neglecting open source so it seemed the best idea was to make you an owner at rubygems and let you work freely. let me know if it works.

**Comment by baschtl** [comment]
@mhfs Works like a charm. Thanks!

**Comment by baschtl** [comment]
I will close this issue as there is apparently no further interest in it.
