### ISSUE TITLE
User Registration Timing Out on Development

### ISSUE THREAD

**Issue by RailsCod3rFuture** [mhfs/devise-async#72]
Do you have a solution for this error? Log below.

Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Redis::TimeoutError)):
  redis (3.2.1) lib/redis/client.rb:331:in `rescue in establish_connection'
  redis (3.2.1) lib/redis/client.rb:317:in `establish_connection'
  redis (3.2.1) lib/redis/client.rb:94:in `block in connect'
  redis (3.2.1) lib/redis/client.rb:279:in `with_reconnect'
  redis (3.2.1) lib/redis/client.rb:93:in `connect'
  redis (3.2.1) lib/redis/client.rb:350:in `ensure_connected'
  redis (3.2.1) lib/redis/client.rb:207:in `block in process'
  redis (3.2.1) lib/redis/client.rb:292:in `logging'
  redis (3.2.1) lib/redis/client.rb:206:in `process'
  redis (3.2.1) lib/redis/client.rb:177:in `call_pipelined'
  redis (3.2.1) lib/redis/client.rb:149:in `block in call_pipeline'
  redis (3.2.1) lib/redis/client.rb:279:in `with_reconnect'
  redis (3.2.1) lib/redis/client.rb:147:in `call_pipeline'
  redis (3.2.1) lib/redis.rb:2182:in `block in multi'
  redis (3.2.1) lib/redis.rb:37:in `block in synchronize'
  C:/Ruby214/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  redis (3.2.1) lib/redis.rb:37:in `synchronize'
  redis (3.2.1) lib/redis.rb:2174:in `multi'
  sidekiq (3.3.3) lib/sidekiq/client.rb:179:in `block in raw_push'
  connection_pool (2.1.3) lib/connection_pool.rb:62:in `with'
  sidekiq (3.3.3) lib/sidekiq/client.rb:178:in `raw_push'
  sidekiq (3.3.3) lib/sidekiq/client.rb:68:in `push'
  sidekiq (3.3.3) lib/sidekiq/worker.rb:84:in `client_push'
  sidekiq (3.3.3) lib/sidekiq/worker.rb:40:in `perform_async'
  devise-async-stretch (0.0.6) lib/devise/async/stretch/backend/sidekiq.rb:11:in `enqueue_job'
  devise-async-stretch (0.0.6) lib/devise/async/stretch/worker.rb:7:in `enqueue'
  devise-async-stretch (0.0.6) lib/devise/async/stretch/model.rb:34:in `enqueue_stre

**Comment by baschtl** [comment]
@RailsCod3rFuture It looks like your connection to Redis - which is used by sidekiq - is not working. So, maybe you want to have a look at https://github.com/mperham/sidekiq to properly set sidekiq up.
