### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by balasankarc** [mhfs/devise-async#76]
Hi,
I am trying to package devise-async for Debian as part of GitLab packaging. While running tests, I got two failures. Can you help me find out what the issue is?

 # Running:

........................F..F....

Finished in 2.304009s, 13.8888 runs/s, 17.3610 assertions/s.

  1) Failure:
Model#test_0004_triggers the enqueued notifications on save [/devise-async/ruby-devise-async-0.9.0/test/devise/async/model_test.rb:50]:
Expected: 1
  Actual: 2

  2) Failure:
Model#test_0003_accumulates notifications to be sent after commit when Model has been changed [/devise-async/ruby-devise-async-0.9.0/test/devise/async/model_test.rb:32]:
Expected: 1
  Actual: 2

32 runs, 40 assertions, 2 failures, 0 errors, 0 skips

**Comment by baschtl** [comment]
@balasankarc That looks weird. Could you give a me a bit more context on your environment (i.e., what gems have you installed, do you use active record or mongoid, etc.)?

**Comment by baschtl** [comment]
@balasankarc If you cannot give me more input I cannot help you there. Sorry.
