### ISSUE TITLE
Gem using outdated version of devise

### ISSUE THREAD

**Issue by djsegal** [mhfs/devise-async#84]
`devise (~> 3.2)` does not allow newest version

**Comment by mikelkew** [comment]
Please consider merging #88 now that Devise 4.0.0 is released.

**Comment by connorshea** [comment]
Just thought I'd mention Devise [can integrate with ActiveJob](https://github.com/plataformatec/devise#activejob-integration) with a bit of configuration, no external gem dependency needed.

**Comment by baschtl** [comment]
Sorry guys, I was busy recently and on holiday. I will try to get this done soon.

**Comment by connorshea** [comment]
@baschtl it may be better to point people towards the Devise integration with ActiveJob I mentioned above. It had a significant bug in 3.6/4.0, but now that 4.1 is out it works flawlessly.

Unless I'm missing something devise-async does that the ActiveJob integration doesn't.
