### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ajeferson** [mhfs/devise-async#91]
Hello, there

I set up everything as the documentation says, but I'm still getting the following error:

`ArgumentError in Devise::PasswordsController#create
wrong number of arguments (given 3, expected 1..2)`

Can anyone help me?

**Comment by jonbcampos** [comment]
I'm seeing this too right now. I am starting to things this gem isn't supported with rails 4.2+ based on the docs

**Comment by jonbcampos** [comment]
figure anything out? anyone watching this with insight?

**Comment by yurijmi** [comment]
Yep, same here

**Comment by yurijmi** [comment]
Hmmm. Somehow i had ```devise-async 0.7.0``` in my bundle. Updated to 0.10.1 and that fixed the issue.

**Comment by yurijmi** [comment]
Try to run ```bundle update```. For some strange reason bundler installed older version of this gem. Updating fixed the problem. And also it's better to use [@klacointe's fork](/klacointe/devise-async/tree/devise4) for Devise 4 support.

**Comment by sdhull** [comment]
So even after `bundle update`, still getting this error.

`wrong number of arguments (given 3, expected 1..2)`

I had to switch my gemfile to use github & the `devise-4x` branch. Now it's working.

**Comment by sreejithponn** [comment]
I hit exactly the same problem..  figured that with sidekiq it is rather easy to implement without needing this gem.
https://github.com/mperham/sidekiq/wiki/Devise

**Comment by Jellyfishboy** [comment]
+1 also seeing this issue

**Comment by swapnilchincholkar** [comment]
Looks like same as #94....

**Comment by TAiS46** [comment]
Still no fix for it?

**Comment by carlosmataguzman** [comment]
@TAiS46 I guess it is still a problem. If you're usign Rails > 4.2 and Devise > 4.0 you could use these 
https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fplataformatec%2Fdevise%23activejob-integration&sa=D&sntz=1&usg=AFQjCNEXWzgYxwI-oArJitXvKE72lidBzg

**Comment by baschtl** [comment]
Closing this as the latest [release](https://github.com/mhfs/devise-async/releases/tag/v1.0.0) depends on ActiveJob. Also have a look into #94 if you are interested in the details.
